apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "helm-chart.name" . }}
  ports:
  - name: comp2envport
    targetPort: 5000
    port: 5000

